### ISSUE TITLE
issure: it cant build on M1

### ISSUE THREAD

**Issue by dll02** [erikdubbelboer/gspt#18]
go build . 
go build github.com/erikdubbelboer/gspt: build constraints exclude all Go files in /Users/xxxx/go/pkg/mod/github.com/erikdubbelboer/gspt@v0.0.0-20210805194459-ce36a5128377
when it build on M1, it report error.

**Comment by erikdubbelboer** [comment]
You're going to have to supply more information. What error, how are you trying to use this lib?

I'm on an M2 (very similar to the M1) and it works perfectly fine here.

**Comment by dll02** [comment]
hi erikdubbelboer ,

it's my project https://github.com/dll02/webgo,i can't go build it and debug it.
➜  webgo git:(main) ✗ go mod tidy
➜  webgo git:(main) ✗ go build .
go build github.com/erikdubbelboer/gspt: build constraints exclude all Go files in /Users/***/go/pkg/mod/github.com/erikdubbelboer/gspt@v0.0.0-20210805194459-ce36a5128377
➜  webgo git:(main) ✗ 

i want use it in the framework/command/app.go, to start app as daemon process.
code like this:
var appStartCommand = &cobra.Command{
	Use:   "start",
	Short: "启动一个app服务",
	RunE: func(c *cobra.Command, args []string) error {
		container := c.GetContainer()
		kernelService := container.MustMake(contract.KernelKey).(contract.Kernel)
		core := kernelService.HttpEngine()

		if appAddress == "" {
			envService := container.MustMake(contract.EnvKey).(contract.Env)
			if envService.Get("ADDRESS") != "" {
				appAddress = envService.Get("ADDRESS")
			} else {
				configService := container.MustMake(contract.ConfigKey).(contract.Config)
				if configService.IsExist("app.address") {
					appAddress = configService.GetString("app.address")
				} else {
					appAddress = ":8888"
				}
			}
		}
		server := &http.Server{
			Handler: core,
			Addr:    appAddress,
		}

		appService := container.MustMake(contract.AppKey).(contract.App)

		pidFolder := appService.RuntimeFolder()
		if !util.Exists(pidFolder) {
			if err := os.MkdirAll(pidFolder, os.ModePerm); err != nil {
				return err
			}
		}
		serverPidFile := filepath.Join(pidFolder, "app.pid")
		logFolder := appService.LogFolder()
		if !util.Exists(logFolder) {
			if err := os.MkdirAll(logFolder, os.ModePerm); err != nil {
				return err
			}
		}
		serverLogFile := filepath.Join(logFolder, "app.log")
		currentFolder := util.GetExecDirectory()
		// daemon
		if appDaemon {
			cntxt := &daemon.Context{
				PidFileName: serverPidFile,
				PidFilePerm: 0664,
				LogFileName: serverLogFile,
				LogFilePerm: 0640,
				WorkDir: currentFolder,
				Umask: 027,
				Args: []string{"", "app", "start", "--daemon=true"},
			}
			d, err := cntxt.Reborn()
			if err != nil {
				return err
			}
			if d != nil {
				fmt.Println("app启动成功，pid:", d.Pid)
				fmt.Println("日志文件:", serverLogFile)
				return nil
			}
			defer cntxt.Release()
			fmt.Println("deamon started")
			gspt.SetProcTitle("webgo app")
			if err := startAppServe(server, container); err != nil {
				fmt.Println(err)
			}
			return nil
		}

		// 非deamon模式，直接执行
		content := strconv.Itoa(os.Getpid())
		fmt.Println("[PID]", content)
		err := ioutil.WriteFile(serverPidFile, []byte(content), 0644)
		if err != nil {
			return err
		}
		gspt.SetProcTitle("webgo app")

		fmt.Println("app serve url:", appAddress)
		if err := startAppServe(server, container); err != nil {
			fmt.Println(err)
		}
		return nil
	},
}

It might just be my other environmental problem, and I'm trying to fix it. 
thanks.

**Comment by erikdubbelboer** [comment]
Have you installed XCode and the command line tools (`xcode-select --install`)?
For me everything works fine on my arm macbook:
```sh
% go version
go version go1.21.0 darwin/arm64

% git clone git@github.com:dll02/webgo.git
Cloning into 'webgo'...

% git diff
diff --git a/framework/command/app.go b/framework/command/app.go
index 51c7f37..23aebc2 100644
--- a/framework/command/app.go
+++ b/framework/command/app.go
@@ -3,13 +3,6 @@ package command
 import (
        "context"
        "fmt"
-       "github.com/dll02/webgo/framework"
-       "github.com/dll02/webgo/framework/cobra"
-       "github.com/dll02/webgo/framework/contract"
-       "github.com/dll02/webgo/framework/util"
-       //"github.com/erikdubbelboer/gspt"
-       "github.com/pkg/errors"
-       "github.com/sevlyar/go-daemon"
        "io/ioutil"
        "net/http"
        "os"
@@ -18,6 +11,14 @@ import (
        "strconv"
        "syscall"
        "time"
+
+       "github.com/dll02/webgo/framework"
+       "github.com/dll02/webgo/framework/cobra"
+       "github.com/dll02/webgo/framework/contract"
+       "github.com/dll02/webgo/framework/util"
+       "github.com/erikdubbelboer/gspt"
+       "github.com/pkg/errors"
+       "github.com/sevlyar/go-daemon"
 )
 
 // app启动地址
@@ -157,7 +158,7 @@ var appStartCommand = &cobra.Command{
                        defer cntxt.Release()
                        // 子进程执行真正的app启动操作
                        fmt.Println("deamon started")
-                       //gspt.SetProcTitle("webgo app")
+                       gspt.SetProcTitle("webgo app")
                        if err := startAppServe(server, container); err != nil {
                                fmt.Println(err)
                        }
@@ -171,7 +172,7 @@ var appStartCommand = &cobra.Command{
                if err != nil {
                        return err
                }
-               //gspt.SetProcTitle("webgo app")
+               gspt.SetProcTitle("webgo app")
 
                fmt.Println("app serve url:", appAddress)
                if err := startAppServe(server, container); err != nil {
--- a/framework/command/cron.go
+++ b/framework/command/cron.go
@@ -2,7 +2,6 @@ package command
 
 import (
        "fmt"
-       "github.com/sevlyar/go-daemon"
        "io/ioutil"
        "os"
        "path/filepath"
@@ -10,9 +9,12 @@ import (
        "syscall"
        "time"
 
+       "github.com/sevlyar/go-daemon"
+
        "github.com/dll02/webgo/framework/cobra"
        "github.com/dll02/webgo/framework/contract"
        "github.com/dll02/webgo/framework/util"
+       "github.com/erikdubbelboer/gspt"
 )
 
 var cronDaemon = false
@@ -107,7 +109,7 @@ var cronStartCommand = &cobra.Command{
                        // 子进程执行Cron.Run
                        defer cntxt.Release()
                        fmt.Println("daemon started")
-                       //gspt.SetProcTitle("hade cron")
+                       gspt.SetProcTitle("hade cron")
                        c.Root().Cron.Run()
                        return nil
                }
@@ -121,7 +123,7 @@ var cronStartCommand = &cobra.Command{
                        return err
                }
 
-               //gspt.SetProcTitle("hade cron")
+               gspt.SetProcTitle("hade cron")
                c.Root().Cron.Run()
                return nil
        },
diff --git a/go.mod b/go.mod
index 2794e20..d180123 100644
--- a/go.mod
+++ b/go.mod
@@ -5,7 +5,7 @@ go 1.18
 require (
        github.com/AlecAivazis/survey/v2 v2.3.7
        github.com/cpuguy83/go-md2man/v2 v2.0.0
-       //github.com/erikdubbelboer/gspt v0.0.0-20210805194459-ce36a5128377
+       github.com/erikdubbelboer/gspt v0.0.0-20210805194459-ce36a5128377
        github.com/fsnotify/fsnotify v1.5.4
        github.com/gin-contrib/cors v1.4.0
        github.com/gin-contrib/sse v0.1.0

% go mod tidy

% go build .

% ./webgo -h
webgo 框架提供的命令行工具，使用这个命令行工具能很方便执行框架自带命令，也能很方便编写业务命令
```

**Comment by chenbihao** [comment]
Does this library only support mac?

**Comment by erikdubbelboer** [comment]
This project should work on any unix type environment such as Mac, Linux, BSD. It won't work on Windows.
