### ISSUE TITLE
Doesn't null terminate string properly?

### ISSUE THREAD

**Issue by hlandau** [erikdubbelboer/gspt#3]
On Linux 3.17.2/glibc 2.20, use of this library doesn't appear to be null-terminating the string properly, so the original command line arguments show through:

    root     25523     1  0 07:03 ?        00:00:00 ncdns: running ok/ncdns.t/bin/ncdns.

**Comment by zygis** [comment]
Dirty fix:
```
package main
import "github.com/ErikDubbelboer/gspt"

func setTitle(title string) {
	length := len(title)
	if length >= 255 {
		length = 255
		gspt.SetProcTitle(title[:255])
	} else {
		title += strings.Repeat(" ", 255-length)
		gspt.SetProcTitle(title)
	}
}

func main() {
	setTitle("spt: ok")
	select{}
}
```

**Comment by Mohanson** [comment]
Have a way to fix? Seems like a mistake on memcpy().

**Comment by erikdubbelboer** [comment]
I just pushed a possible fix. I don't have a system with systemd to test this with. Can you test it.

**Comment by Mohanson** [comment]
It's OK.

```golang
package main

import (
  "github.com/erikdubbelboer/gspt"
)

func main() {
  gspt.SetProcTitle("^")
  select{}
}
```
`go run *.go`

Before Hopefully fix: 
`root     19348  0.0  0.1  25744  1424 pts/0    Sl+  11:39   0:00 ^tmp/go-build424486571/command-line-arguments/_obj/exe/app.`
And now:
`root     19456  0.0  0.1  25744  1424 pts/0    Sl+  11:40   0:00 ^`

**Comment by erikdubbelboer** [comment]
Great.
