### ISSUE TITLE
Why i see the dot at the end of process title?

### ISSUE THREAD

**Issue by halturin** [erikdubbelboer/gspt#9]
Hi

I'm using Debian 9 and every single process i have renamed has the dot at the end of line.

I didn't inspect the code logic yet and have decided to ask you before go deeper. I found this one at the source https://github.com/erikdubbelboer/gspt/blob/master/setproctitle.h#L236

Could you explain, why you set the dot at the end of process title?

**Comment by halturin** [comment]
here is how it looks like
![image](https://user-images.githubusercontent.com/118860/32717434-ae4f9776-c86a-11e7-9d72-ffa0c14df42a.png)

**Comment by halturin** [comment]
Please, have a look possible solutions

here the line, i mentioned earlier, replaced by setting zero character till the end of line.
https://github.com/ramaxlo/gspt/commit/de6c2540da4341002154d9d14acd7d1939efa66e

and this solution just fill the rest of line by space character.
https://github.com/friendwu/gspt/commit/a407912991b2c6d46278866d5b044c59941382fb

i didn't check these solutions out, but you could use as the solution if you confirm that the 'dot' is the bug :)

**Comment by erikdubbelboer** [comment]
I have merged the fix by @ramaxlo . Hope that helps.
